markdown: kramdown
kramdown:
    input: GFM

safe: true
lsi: false

exclude:
    - "bin"
    - "vendor"

sass:
    style: compressed

url: "http://toni.uebernickel.info"
baseurl: ""

title: havvg's playground
description: Developing Software is Fun!

logo: /images/logo.jpg
cover:
  top: /images/cover.jpg
  bottom: /images/cover.jpg

author:
  name: Toni Uebernickel
  email: tuebernickel@gmail.com
  image: /images/profile_photo.jpg
  bio: Software Engineer and Architect, Symfony and Propel evangelist with some Ducati bikes.
  social:
    - icon: github
      url: https://github.com/havvg
      desc: Fork me on github

    - icon: twitter
      url: https://twitter.com/havvg
      desc: Follow me on twitter

    - icon: linkedin
      url: https://www.linkedin.com/in/havvg
      desc: Connect on LinkedIn

    - icon: xing
      url: https://www.xing.com/profile/Toni_Uebernickel
      desc: Connect on XING

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      comments: false

disqus:
  config:
    - label: disqus_shortname
      value: 'havvgsplayground'

googleanalytics:
  account: UA-738346-7

gosquared:
  account: GSN-841923-G
